// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzsGtT5OFTVwFgPEtST_RXow2Oc-nglU',
    appId: '1:544457252112:web:263c1bd049b12727fc9995',
    messagingSenderId: '544457252112',
    projectId: 'mobile-53dc7',
    authDomain: 'mobile-53dc7.firebaseapp.com',
    storageBucket: 'mobile-53dc7.appspot.com',
    measurementId: 'G-5QNT5SHZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfO4dfdhLKwIYb_wjTtlyAkfBZQLHeUMY',
    appId: '1:544457252112:android:ac070ce6d25be27cfc9995',
    messagingSenderId: '544457252112',
    projectId: 'mobile-53dc7',
    storageBucket: 'mobile-53dc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbfFDdXiNiE4XpVqjEiXK6A_k_J-65-Vo',
    appId: '1:544457252112:ios:438f0a8dfcbcea8afc9995',
    messagingSenderId: '544457252112',
    projectId: 'mobile-53dc7',
    storageBucket: 'mobile-53dc7.appspot.com',
    iosClientId: '544457252112-f18d9s0bkn46l4vm6pl2jdfnjtefifml.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbfFDdXiNiE4XpVqjEiXK6A_k_J-65-Vo',
    appId: '1:544457252112:ios:438f0a8dfcbcea8afc9995',
    messagingSenderId: '544457252112',
    projectId: 'mobile-53dc7',
    storageBucket: 'mobile-53dc7.appspot.com',
    iosClientId: '544457252112-f18d9s0bkn46l4vm6pl2jdfnjtefifml.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
